# Generated by Django 4.0.4 on 2022-05-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    def create_person(apps, schema_editor):
        Tier = apps.get_model('app_image', 'Tier')
        Tier.objects.create(name='Basic', is_thumbnail_200=True)
        Tier.objects.create(name='Premium', is_thumbnail_200=True, is_thumbnail_400=True)
        Tier.objects.create(
            name='Enterprise',
            is_thumbnail_200=True,
            is_thumbnail_400=True,
            is_original_link=True,
            is_time_exist=True
        )


    dependencies = [
        ('app_image', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_person)
    ]
