# Generated by Django 4.0.4 on 2022-05-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    def create_person(apps, schema_editor):
        ThumbnailSize = apps.get_model("app_image", "ThumbnailSize")
        size_200 = ThumbnailSize.objects.create(size=200)
        size_400 = ThumbnailSize.objects.create(size=400)

        Tier = apps.get_model("app_image", "Tier")

        tier_basic = Tier.objects.create(name="Basic")
        tier_basic.thumbnail_sizes.add(size_200)

        tier_premium = Tier.objects.create(name="Premium")
        tier_premium.thumbnail_sizes.add(size_200, size_400)

        tier_enterprise = Tier.objects.create(
            name="Enterprise",
            is_original_link=True
        )
        tier_enterprise.thumbnail_sizes.add(size_200, size_400)

    dependencies = [
        ("app_image", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_person)
    ]
